### ISSUE TITLE
[Brave New World] Cheating

### ISSUE THREAD

**Issue by hasezoey** [canidae/factorio#5] opened 2018-01-03 12:35 UTC
if the player goes to the end (where the player /vehicle will be teleportet back) the player can go into the map and use the new loaded chunks to build + generates new chunk

**Comment by canidae** [comment] 2018-01-10 06:46
I've had some issues where the player could explore some chunks by moving to the edge of the allowed area. I'll see what I can do about this.

**Comment by canidae** [comment] 2018-01-10 17:14
I know that the player can build outside of radar coverage, but I won't try to prevent this. It'll just be confusing for the users and they still need roboport coverage to build anything.
Exploration on the other hand I want to prevent, although after some brief testing I've not been able to explore new chunks by moving to the edge of the allowed area for the player. I'll keep an eye on it, but if I can't reproduce it I'll close this issue.

**Comment by canidae** [comment] 2018-01-12 16:18
Managed to reproduce exploration of unscanned chunks. Will look into this.

**Comment by canidae** [comment] 2018-01-12 19:09
This will be fixed for BNW 2.0.0. Thanks for the report!

**Closed as completed by canidae** 2018-01-12 19:09 UTC
